name: Test ETL Pipeline

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (don not commit changes)'
        required: false
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'

jobs:
  test-etl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test ETL Pipeline
      run: |
        echo "🧪 Testing ETL Pipeline..."
        python etl.py
        echo "✅ ETL completed successfully"
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Show generated data
      run: |
        echo "📊 Generated Data Summary:"
        if [ -f "public/data/summary.json" ]; then
          cat public/data/summary.json | jq '.'
        fi
        
        echo ""
        echo "📈 Sample Data (first 2 companies):"
        if [ -f "public/data/weekly_stats.json" ]; then
          cat public/data/weekly_stats.json | jq '.data[:2]'
        fi
    
    - name: Commit changes (if not dry run)
      if: github.event.inputs.dry_run != 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action (Test)"
        git add public/data/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🧪 Test ETL run - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: etl-output
        path: public/data/
        retention-days: 7